services:
  nginx-proxy:
    environment:
      DOCKER_HOST: unix:///tmp/docker.sock
      INDEX_HOST: server1
      INDEX_NAME: Index Page
      INDEX_DESC: This is the index page
      INDEX_GROUP: default
      VIRTUAL_HOST: index.dev.localhost
      VIRTUAL_PORT: 80
    container_name: index
    image: perbohlin/nginx-proxy-index:test
    restart: always
    ports:
      - 8082:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
