services:
  nginx-proxy:
    environment:
      DOCKER_HOST: unix:///tmp/docker.sock
      INDEX_HOST: server1
      VIRTUAL_HOST: index.dev.localhost
      VIRTUAL_PORT: 80
    container_name: index
    image: perbohlin/nginx-proxy-index:test
    restart: always
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
